# Generated by Django 5.2.7 on 2025-11-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_member',
            field=models.BooleanField(default=False, help_text='Arche 교회 등록 교인인 경우 체크', verbose_name='Arche 교인 여부'),
        ),
    ]
