# Generated by Django 5.2.7 on 2025-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('obedience', '순종'), ('faith', '믿음'), ('love', '사랑'), ('repentance', '회개'), ('comfort', '위로'), ('peace', '평안'), ('prayer', '기도'), ('acceptance', '영접'), ('hope', '소망'), ('grace', '은혜'), ('forgiveness', '용서'), ('wisdom', '지혜'), ('courage', '용기'), ('thanksgiving', '감사')], max_length=20, verbose_name='카테고리')),
                ('reference_kr', models.CharField(max_length=100, verbose_name='성경 참조 (한글)')),
                ('reference_de', models.CharField(max_length=100, verbose_name='성경 참조 (독일어)')),
                ('text_kr', models.TextField(verbose_name='한글 구절 (개역개정)')),
                ('text_de', models.TextField(verbose_name='독일어 구절 (Schlachter 2000)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('priority', models.IntegerField(default=1, help_text='1-10 (낮을수록 자주 표시됨)', verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '성경 구절',
                'verbose_name_plural': '성경 구절 목록',
                'ordering': ['priority', 'category'],
            },
        ),
    ]
