# Generated by Django 5.2.7 on 2026-04-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_verses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JesusSaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('MAT', '마태복음'), ('MRK', '마가복음'), ('LUK', '누가복음'), ('JHN', '요한복음')], max_length=3, verbose_name='복음서')),
                ('chapter', models.PositiveSmallIntegerField(verbose_name='장')),
                ('verse_start', models.PositiveSmallIntegerField(verbose_name='시작 절')),
                ('verse_end', models.PositiveSmallIntegerField(verbose_name='끝 절')),
                ('size', models.CharField(choices=[('S', '단문 (1~2절)'), ('M', '중문 (3~8절)'), ('L', '장문 (9절 이상)')], default='M', max_length=1, verbose_name='말씀 크기')),
                ('text_ko_krv', models.TextField(verbose_name='개역개정')),
                ('text_ko_new', models.TextField(blank=True, verbose_name='새번역')),
                ('text_en', models.TextField(blank=True, verbose_name='영어 (NIV)')),
                ('text_de', models.TextField(blank=True, verbose_name='독일어 (Schlachter)')),
                ('text_zh', models.TextField(blank=True, verbose_name='중국어')),
                ('text_es', models.TextField(blank=True, verbose_name='스페인어')),
                ('context_ko', models.TextField(blank=True, help_text='말씀의 상황·배경을 2~4문장으로 설명', verbose_name='배경 설명 (한국어)')),
                ('context_en', models.TextField(blank=True, verbose_name='배경 설명 (영어)')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='원어(헬라어/히브리어) 단어 설명 JSON 배열', verbose_name='핵심 단어')),
                ('audience', models.CharField(choices=[('disciples', '제자들'), ('pharisees', '바리새인 / 서기관'), ('crowd', '무리'), ('individual', '개인'), ('prayer', '기도 (아버지께)'), ('mixed', '혼합')], default='mixed', max_length=20, verbose_name='청중')),
                ('occasion', models.CharField(blank=True, help_text='예: 산상수훈, 최후의 만찬, 나사로 사건', max_length=100, verbose_name='사건/상황')),
                ('season', models.CharField(choices=[('advent', '대강절 (12월)'), ('christmas', '성탄절'), ('lent', '사순절 (2~3월)'), ('easter', '부활절'), ('pentecost', '성령강림절'), ('ordinary', '평시')], default='ordinary', max_length=20, verbose_name='절기')),
                ('slide_cycle', models.PositiveSmallIntegerField(default=1, help_text='1 또는 2', verbose_name='슬라이드 사이클')),
                ('slide_order', models.PositiveIntegerField(default=0, help_text='사이클 내 표시 순서', verbose_name='슬라이드 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '예수님 말씀',
                'verbose_name_plural': '예수님 말씀 목록',
                'ordering': ['book', 'chapter', 'verse_start'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('i_am', '나는 ~이다 선언'), ('salvation', '영생 / 구원'), ('kingdom', '하나님 나라'), ('love', '사랑 / 계명'), ('prayer', '기도'), ('faith', '믿음'), ('holy_spirit', '성령'), ('discipleship', '제자도'), ('cross', '십자가 / 고난'), ('resurrection', '부활'), ('judgment', '심판'), ('forgiveness', '용서'), ('healing', '치유 / 기적'), ('identity', '예수님의 정체')], max_length=30, unique=True, verbose_name='주제 키')),
                ('name_ko', models.CharField(max_length=50, verbose_name='한국어 이름')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='영어 이름')),
                ('name_de', models.CharField(blank=True, max_length=50, verbose_name='독일어 이름')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '주제',
                'verbose_name_plural': '주제 목록',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='묵상 내용')),
                ('is_private', models.BooleanField(default=True, help_text='True: 본인만 / False: 그룹 공유', verbose_name='비공개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to='bible_verses.jesussaying', verbose_name='말씀')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '묵상 노트',
                'verbose_name_plural': '묵상 노트 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParallelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 주기도문, 베드로의 고백, 씨 뿌리는 비유', max_length=100, verbose_name='그룹 이름')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
                ('sayings', models.ManyToManyField(blank=True, related_name='parallel_groups', to='bible_verses.jesussaying', verbose_name='병행 말씀들')),
            ],
            options={
                'verbose_name': '병행구절 그룹',
                'verbose_name_plural': '병행구절 그룹 목록',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='jesussaying',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='sayings', to='bible_verses.theme', verbose_name='주제 태그'),
        ),
        migrations.AlterUniqueTogether(
            name='jesussaying',
            unique_together={('book', 'chapter', 'verse_start')},
        ),
    ]
