# Generated by Django 5.2.7 on 2026-04-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_verses', '0002_jesussaying_theme_meditation_parallelgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='묵상 날짜'),
        ),
    ]
