# Generated by Django 5.2.7 on 2025-11-23 20:44

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='포스트 대표 이미지 (선택사항)', null=True, upload_to=board.models.post_image_path, verbose_name='대표 이미지'),
        ),
    ]
