# Generated by Django 5.2.7 on 2025-11-27 09:05

import django.core.validators
import django.db.models.deletion
import pastoral_letters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('letter_date', models.DateField(help_text='목회서신 발행 날짜', verbose_name='서신 날짜')),
                ('pdf_file', models.FileField(help_text='한국어로 번역된 목회서신 PDF', upload_to=pastoral_letters.models.pastoral_letter_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='번역본 PDF')),
                ('description', models.TextField(blank=True, help_text='목회서신 내용 요약 (선택사항)', verbose_name='요약')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '목회서신',
                'verbose_name_plural': '목회서신 목록',
                'ordering': ['-letter_date', '-created_at'],
                'indexes': [models.Index(fields=['-letter_date'], name='pastoral_le_letter__166fa6_idx'), models.Index(fields=['created_at'], name='pastoral_le_created_56cffa_idx')],
            },
        ),
    ]
