# Generated by Django 5.2.7 on 2025-11-17 12:00

import django.core.validators
import django.db.models.deletion
import sermons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='설교 제목')),
                ('preacher', models.CharField(max_length=100, verbose_name='설교자')),
                ('sermon_date', models.DateField(verbose_name='설교일')),
                ('category', models.CharField(choices=[('sunday', '주일예배'), ('wednesday', '수요예배'), ('friday', '금요예배'), ('special', '특별예배'), ('revival', '부흥회'), ('seminar', '세미나'), ('other', '기타')], default='sunday', max_length=20, verbose_name='카테고리')),
                ('bible_book', models.CharField(choices=[('genesis', '창세기'), ('exodus', '출애굽기'), ('leviticus', '레위기'), ('numbers', '민수기'), ('deuteronomy', '신명기'), ('joshua', '여호수아'), ('judges', '사사기'), ('ruth', '룻기'), ('1samuel', '사무엘상'), ('2samuel', '사무엘하'), ('1kings', '열왕기상'), ('2kings', '열왕기하'), ('1chronicles', '역대상'), ('2chronicles', '역대하'), ('ezra', '에스라'), ('nehemiah', '느헤미야'), ('esther', '에스더'), ('job', '욥기'), ('psalms', '시편'), ('proverbs', '잠언'), ('ecclesiastes', '전도서'), ('song', '아가'), ('isaiah', '이사야'), ('jeremiah', '예레미야'), ('lamentations', '예레미야애가'), ('ezekiel', '에스겔'), ('daniel', '다니엘'), ('hosea', '호세아'), ('joel', '요엘'), ('amos', '아모스'), ('obadiah', '오바댜'), ('jonah', '요나'), ('micah', '미가'), ('nahum', '나훔'), ('habakkuk', '하박국'), ('zephaniah', '스바냐'), ('haggai', '학개'), ('zechariah', '스가랴'), ('malachi', '말라기'), ('matthew', '마태복음'), ('mark', '마가복음'), ('luke', '누가복음'), ('john', '요한복음'), ('acts', '사도행전'), ('romans', '로마서'), ('1corinthians', '고린도전서'), ('2corinthians', '고린도후서'), ('galatians', '갈라디아서'), ('ephesians', '에베소서'), ('philippians', '빌립보서'), ('colossians', '골로새서'), ('1thessalonians', '데살로니가전서'), ('2thessalonians', '데살로니가후서'), ('1timothy', '디모데전서'), ('2timothy', '디모데후서'), ('titus', '디도서'), ('philemon', '빌레몬서'), ('hebrews', '히브리서'), ('james', '야고보서'), ('1peter', '베드로전서'), ('2peter', '베드로후서'), ('1john', '요한1서'), ('2john', '요한2서'), ('3john', '요한3서'), ('jude', '유다서'), ('revelation', '요한계시록')], max_length=50, verbose_name='성경')),
                ('chapter', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='장')),
                ('verse_start', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='시작 절')),
                ('verse_end', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='마지막 절')),
                ('audio_file', models.FileField(help_text='통역된 설교 오디오 파일', upload_to=sermons.models.sermon_audio_path, verbose_name='통역 MP3 파일')),
                ('original_pdf', models.FileField(blank=True, help_text='원본 설교 자료', null=True, upload_to=sermons.models.sermon_pdf_path, verbose_name='원본 PDF')),
                ('translated_pdf', models.FileField(blank=True, help_text='번역된 설교 자료', null=True, upload_to=sermons.models.sermon_pdf_path, verbose_name='번역 PDF')),
                ('description', models.TextField(blank=True, help_text='설교 내용 요약 (선택사항)', verbose_name='설교 요약')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='오디오 파일 재생 시간', null=True, verbose_name='재생 시간(초)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '설교',
                'verbose_name_plural': '설교 목록',
                'ordering': ['-sermon_date', '-created_at'],
                'indexes': [models.Index(fields=['-sermon_date'], name='sermons_ser_sermon__218096_idx'), models.Index(fields=['category'], name='sermons_ser_categor_3703fc_idx'), models.Index(fields=['preacher'], name='sermons_ser_preache_8d4137_idx')],
            },
        ),
    ]
