# Generated by Django 5.2.7 on 2025-11-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='category',
            field=models.CharField(choices=[('sunday', '주일예배'), ('youth', '청소년예배'), ('special', '특별예배'), ('conference', '컨퍼런스'), ('seminar', '세미나'), ('other', '기타')], default='sunday', max_length=20, verbose_name='카테고리'),
        ),
    ]
