# Generated by Django 5.2.7 on 2025-11-27 09:08

import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_alter_sermon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='통역된 설교 오디오 파일', null=True, upload_to=sermons.models.sermon_audio_path, verbose_name='통역 MP3 파일'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='translated_pdf',
            field=models.FileField(default='', help_text='번역된 설교 자료', upload_to=sermons.models.sermon_pdf_path, verbose_name='번역 PDF'),
            preserve_default=False,
        ),
    ]
