# Generated by Django 5.2.7 on 2025-12-01 10:00

import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_alter_sermon_audio_file_alter_sermon_translated_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='original_audio_file',
            field=models.FileField(blank=True, help_text='설교자의 원본 설교 음성 파일 (독일어)', null=True, upload_to=sermons.models.sermon_original_audio_path, verbose_name='원본 설교 오디오'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='통역된 설교 오디오 파일 (한국어)', null=True, upload_to=sermons.models.sermon_audio_path, verbose_name='통역 MP3 파일'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='original_pdf',
            field=models.FileField(blank=True, help_text='원본 설교 자료 (독일어)', null=True, upload_to=sermons.models.sermon_pdf_path, verbose_name='원본 PDF'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='translated_pdf',
            field=models.FileField(blank=True, help_text='번역된 설교 자료 (한국어)', null=True, upload_to=sermons.models.sermon_pdf_path, verbose_name='번역 PDF'),
        ),
    ]
