# Generated by Django 5.2.7 on 2025-12-02 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='회의 제목')),
                ('description', models.TextField(blank=True, verbose_name='회의 설명')),
                ('status', models.CharField(choices=[('waiting', '대기중'), ('active', '진행중'), ('ended', '종료됨')], default='waiting', max_length=20, verbose_name='상태')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='최대 참가자 수')),
                ('password', models.CharField(blank=True, help_text='선택사항: 비밀번호 보호', max_length=50, verbose_name='비밀번호')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='예정 시간')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL, verbose_name='방장')),
            ],
            options={
                'verbose_name': '화상회의방',
                'verbose_name_plural': '화상회의방 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice-candidate', 'ICE Candidate')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='video_meetings.videoroom')),
            ],
            options={
                'verbose_name': '시그널 메시지',
                'verbose_name_plural': '시그널 메시지 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '승인대기'), ('approved', '승인됨'), ('rejected', '거부됨'), ('left', '퇴장함')], default='pending', max_length=20, verbose_name='참가 상태')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='입장 시간')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='퇴장 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='video_meetings.videoroom')),
            ],
            options={
                'verbose_name': '참가자',
                'verbose_name_plural': '참가자 목록',
                'ordering': ['created_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
