# Generated by Django 5.2.7 on 2025-12-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='screen_sharing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharing_screen_in', to=settings.AUTH_USER_MODEL, verbose_name='화면 공유 중'),
        ),
        migrations.AlterField(
            model_name='signalmessage',
            name='message_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE Candidate'), ('approval', 'Approval'), ('screen_share_start', 'Screen Share Start'), ('screen_share_stop', 'Screen Share Stop'), ('reaction', 'Reaction'), ('raise_hand', 'Raise Hand'), ('chat_message', 'Chat Message')], max_length=30),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '텍스트'), ('file', '파일'), ('system', '시스템')], default='text', max_length=20)),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='video_meetings.videoroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('👍', '좋아요'), ('👏', '박수'), ('❤️', '하트'), ('😂', '웃음'), ('🎉', '축하'), ('🤔', '생각중')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='video_meetings.videoroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '반응',
                'verbose_name_plural': '반응 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaisedHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('lowered_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_hands', to='video_meetings.videoroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_hands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '손들기',
                'verbose_name_plural': '손들기 목록',
                'ordering': ['raised_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
