# Generated by Django 5.2.7 on 2025-12-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_meetings', '0002_videoroom_screen_sharing_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raisedhand',
            name='raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
